import Badge from './Badge.jsx';

// Funnel stages are one series — magnitude is carried by bar length, so colour
// stays constant across bars. Colouring by stage would encode rank, not entity.
const STAGES = [
  { key: 'inquiries', label: 'Inquiries' },
  { key: 'warm', label: 'Reached warm' },
  { key: 'hot', label: 'Reached hot' },
  { key: 'converted', label: 'Converted' },
];

const pct = (n, total) => (total > 0 ? Math.round((n / total) * 100) : 0);

export default function Dashboard({ funnel, loading, onRefreshInsight, onOpenConversation }) {
  if (!funnel) {
    return (
      <div className="empty">
        <h3>{loading ? 'Loading funnel…' : 'No funnel data'}</h3>
        <p>Send some DMs from the Inbox tab first.</p>
      </div>
    );
  }

  const { counts, avgResponseMs, sampleSize, hotConversations, insight, insightError } = funnel;
  const total = counts.inquiries;

  // The largest stage-to-stage drop — named in the copy so the chart has a point.
  let biggestDrop = null;
  for (let i = 1; i < STAGES.length; i += 1) {
    const lost = counts[STAGES[i - 1].key] - counts[STAGES[i].key];
    if (!biggestDrop || lost > biggestDrop.lost) {
      biggestDrop = { lost, from: STAGES[i - 1].label, to: STAGES[i].label };
    }
  }

  const avgSeconds = avgResponseMs != null ? (avgResponseMs / 1000).toFixed(1) : null;

  return (
    <div className="dash viz-root">
      {/* KPI row — four headline numbers, so stat tiles rather than a chart. */}
      <div className="kpis">
        {STAGES.map((s) => (
          <div className="kpi" key={s.key}>
            <div className="kpi-label">{s.label}</div>
            <div className="kpi-value">{counts[s.key]}</div>
            <div className="kpi-sub">
              {s.key === 'inquiries' ? 'this week' : `${pct(counts[s.key], total)}% of inquiries`}
            </div>
          </div>
        ))}
      </div>

      <div className="dash-grid">
        <section className="card">
          <h3 className="card-title">Funnel</h3>
          <p className="card-note">
            {biggestDrop && biggestDrop.lost > 0
              ? `Biggest drop-off: ${biggestDrop.lost} lost between ${biggestDrop.from} and ${biggestDrop.to}.`
              : 'No drop-off yet.'}
          </p>
          <div className="bars">
            {STAGES.map((s) => (
              <div className="bar-row" key={s.key}>
                <div className="bar-label">{s.label}</div>
                <div className="bar-track">
                  <div
                    className="bar-fill"
                    style={{ width: `${total > 0 ? (counts[s.key] / total) * 100 : 0}%` }}
                  />
                </div>
                <div className="bar-value">{counts[s.key]}</div>
              </div>
            ))}
          </div>
        </section>

        <section className="card">
          <h3 className="card-title">Response time</h3>
          <p className="card-note">
            {avgSeconds
              ? `Measured mean of ${sampleSize} first replies: ${avgSeconds}s.`
              : 'No replies measured yet.'}
          </p>
          <div className="bars">
            <div className="bar-row">
              <div className="bar-label">WHATSY (AI)</div>
              <div className="bar-track">
                <div className="bar-fill" style={{ width: '2%' }} />
              </div>
              <div className="bar-value">{avgSeconds ? `${avgSeconds}s` : '—'}</div>
            </div>
            <div className="bar-row">
              <div className="bar-label">James, by hand</div>
              <div className="bar-track">
                <div className="bar-fill is-alt" style={{ width: '100%' }} />
              </div>
              <div className="bar-value">~4h</div>
            </div>
          </div>
          <p className="card-foot">
            The AI figure is real, measured round-trip time. The 4-hour manual baseline is an
            illustrative stand-in, not measured data.
          </p>
        </section>
      </div>

      <section className="card card-insight">
        <div className="card-title-row">
          <h3 className="card-title">Claude's read on the week</h3>
          <button className="btn btn-small" onClick={onRefreshInsight} disabled={loading}>
            ↻ Regenerate
          </button>
        </div>
        {insightError ? (
          <p className="insight-error">Insight unavailable: {insightError}</p>
        ) : insight ? (
          <>
            <p className="insight">{insight.insight}</p>
            <p className="card-foot">
              Generated by {insight.cached ? 'Claude (cached for these counts)' : 'Claude just now'}.
            </p>
          </>
        ) : (
          <p className="card-foot">No insight yet — send some DMs first.</p>
        )}
      </section>

      <section className="card">
        <h3 className="card-title">Hot conversations ({hotConversations.length})</h3>
        {hotConversations.length === 0 ? (
          <p className="card-foot">Nothing hot right now.</p>
        ) : (
          <ul className="hot-list">
            {hotConversations.map((h) => (
              <li className="hot-item" key={h.id}>
                <div className="hot-top">
                  <strong>{h.buyerName}</strong>
                  <span className="conv-handle">{h.buyerHandle}</span>
                  <Badge status={h.status} />
                  {h.converted && <span className="pill-paid">payment link sent</span>}
                  <button className="btn btn-small" onClick={() => onOpenConversation(h.id)}>
                    View conversation →
                  </button>
                </div>
                <div className="hot-summary">{h.hotSummary || h.item || 'No summary yet.'}</div>
              </li>
            ))}
          </ul>
        )}
      </section>
    </div>
  );
}
